import { TestCaseGroup } from "../test-plan.model";

export const TEST_CASE_GROUP_DATA: TestCaseGroup[] = [
  {
    id: 1,
    index: "1",
    name: "Functional",
    author_id: 1,
    parent_id: 0,
    project_id: 1,
    test_plan_id: 1,
    isGroupBy: true,
    created: new Date("2020-05-23"),
  },
  {
    id: 2,
    index: "1.1",
    name: "Functional > UI",
    author_id: 1,
    parent_id: 1,
    project_id: 1,
    test_plan_id: 1,
    isGroupBy: true,
    created: new Date("2020-05-23"),
  },
  {
    id: 3,
    index: "1.2",
    name: "Functional > CUJ",
    author_id: 1,
    parent_id: 1,
    project_id: 1,
    test_plan_id: 1,
    isGroupBy: true,
    created: new Date("2020-05-23"),
  },
  {
    id: 4,
    index: "2",
    name: "Performance",
    author_id: 1,
    parent_id: 0,
    project_id: 1,
    test_plan_id: 1,
    isGroupBy: true,
    created: new Date("2020-05-23"),
  },
  {
    id: 5,
    index: "2.1",
    name: "Performance > Network",
    author_id: 1,
    parent_id: 4,
    project_id: 1,
    test_plan_id: 1,
    isGroupBy: true,
    created: new Date("2020-05-23"),
  },
  {
    id: 6,
    index: "3",
    name: "Security",
    author_id: 1,
    parent_id: 0,
    project_id: 1,
    test_plan_id: 1,
    isGroupBy: true,
    created: new Date("2020-05-23"),
  },
];
