import { TestCase } from "../test-plan.model";

export const TEST_CASE_DATA: TestCase[] = [
  {
    id: 1,
    index: 1,
    title: "Verify if a User can sign in with a newly created account",
    priority: "P2",
    status: "NEW",
    steps: "1. Do something\n2. Then do something else\nVRF: AAA is not green",
    tags: [],
    author_id: 1,
    project_id: 1,
    test_plan_id: 1,
    created: new Date("2020-05-23"),
  },
  {
    id: 2,
    index: 2,
    title: "Verify if already created User can sign in",
    priority: "P2",
    status: "PASSED",
    steps: "",
    tags: [],
    author_id: 1,
    project_id: 1,
    test_plan_id: 1,
    created: new Date("2020-05-23"),
  },
  {
    id: 3,
    index: 3,
    title: "Verify event recurring event creation with custom recurring rule",
    priority: "P2",
    status: "FAILED",
    steps: "",
    tags: [],
    author_id: 1,
    project_id: 1,
    test_plan_id: 1,
    created: new Date("2020-05-23"),
  },
  {
    id: 4,
    index: 4,
    title: "Test case A",
    priority: "P2",
    status: "BLOCKED",
    steps: "",
    tags: [],
    author_id: 1,
    project_id: 1,
    test_plan_id: 1,
    created: new Date("2020-05-23"),
  },
  {
    id: 5,
    index: 5,
    title: "Test case B",
    priority: "P2",
    status: "SKIPPED",
    steps: "",
    tags: [],
    author_id: 1,
    project_id: 1,
    test_plan_id: 1,
    created: new Date("2020-05-23"),
  },
  {
    id: 6,
    index: 6,
    title: "Test case C",
    priority: "P2",
    status: "NEW",
    steps: "",
    tags: [],
    author_id: 1,
    project_id: 1,
    test_plan_id: 1,
    created: new Date("2020-05-23"),
  },
  {
    id: 7,
    index: 7,
    title: "Test case D",
    priority: "P2",
    status: "NEW",
    steps: "",
    tags: [],
    author_id: 1,
    project_id: 1,
    test_plan_id: 1,
    created: new Date("2020-05-23"),
  },
  {
    id: 8,
    index: 8,
    title: "Test case E",
    priority: "P2",
    status: "NEW",
    steps: "",
    tags: [],
    author_id: 1,
    project_id: 1,
    test_plan_id: 1,
    created: new Date("2020-05-23"),
  },
];
